<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <PackageId>DDCSharp.Core</PackageId>
    <Description>Core abstractions and capabilities for controlling monitors via DDC/CI in .NET.</Description>
    <PackageTags>DDC;DDC/CI;Monitor;Display;VCP;Brightness</PackageTags>
  </PropertyGroup>

</Project>
