<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <PackageId>DDCSharp.Linux</PackageId>
    <Description>Linux implementation for DDCSharp providing monitor enumeration and DDC/CI over /dev/i2c-*.</Description>
    <PackageTags>DDC;DDC/CI;Monitor;Display;VCP;Linux;I2C</PackageTags>
  </PropertyGroup>

  <ItemGroup>
    <AssemblyAttribute Include="System.Runtime.Versioning.SupportedOSPlatformAttribute">
      <_Parameter1>linux</_Parameter1>
    </AssemblyAttribute>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\DDCSharp.Core\DDCSharp.Core.csproj" />
  </ItemGroup>

</Project>
